// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.bocsh.protobuf;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bocsh.proto.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>string desc = 4;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>repeated .com.bocsh.proto.User.Role roles = 5;</code>
   */
  java.util.List<com.bocsh.protobuf.User.Role> 
      getRolesList();
  /**
   * <code>repeated .com.bocsh.proto.User.Role roles = 5;</code>
   */
  com.bocsh.protobuf.User.Role getRoles(int index);
  /**
   * <code>repeated .com.bocsh.proto.User.Role roles = 5;</code>
   */
  int getRolesCount();
  /**
   * <code>repeated .com.bocsh.proto.User.Role roles = 5;</code>
   */
  java.util.List<? extends com.bocsh.protobuf.User.RoleOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <code>repeated .com.bocsh.proto.User.Role roles = 5;</code>
   */
  com.bocsh.protobuf.User.RoleOrBuilder getRolesOrBuilder(
      int index);
}
