// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.bocsh.protobuf;

public final class Users {
  private Users() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocsh_proto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocsh_proto_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bocsh_proto_User_Role_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bocsh_proto_User_Role_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\017com.bocsh.proto\"\226\001\n\004User\022\n" +
      "\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\014\n" +
      "\004desc\030\004 \001(\t\022)\n\005roles\030\005 \003(\0132\032.com.bocsh.p" +
      "roto.User.Role\032.\n\004Role\022\n\n\002id\030\001 \001(\t\022\014\n\004na" +
      "me\030\002 \001(\t\022\014\n\004desc\030\003 \001(\tB\035\n\022com.bocsh.prot" +
      "obufB\005UsersP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bocsh_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bocsh_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocsh_proto_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Desc", "Roles", });
    internal_static_com_bocsh_proto_User_Role_descriptor =
      internal_static_com_bocsh_proto_User_descriptor.getNestedTypes().get(0);
    internal_static_com_bocsh_proto_User_Role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bocsh_proto_User_Role_descriptor,
        new java.lang.String[] { "Id", "Name", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
